services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    env_file:
      - ./env/.env
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    depends_on:
      - backend